#!/bin/bash

if [ ! -f "$1" ]
then
    echo 'You need to summpy a file with service names'
    exit 1
fi

services=($(cat $1))
echo

for service in ${services[@]}
do
    printf '%-80s\r' "resetting service: $service"
    adb shell dumpsys $service --reset 1>/dev/null
done

echo
