#!/bin/bash

if [ ! -f "$1" ]
then
    echo 'You need to summpy a file with service names'
    exit 1
fi

services=($(cat $1))
printf '[RESTARTING SERVICE]'

for service in ${services[@]}
do
    printf '%80s\r' '' "$service"
    adb shell dumpsys $service --reset &>/dev/null
done

printf '\n'
