#!/bin/bash

if [ "$1" != 'olx' ] && [ "$1" != 'icarwash' ]
then
    echo "Unknown test suite $1"
    exit 1
fi

files=$(find "../test/$1" -iname mt*.txt | sort)
package='pl.grzeniu.mt'
activity='ItemListActivity'

for file in ${files[@]}
do
    echo "running steps for $file"
    monkeyrunner run-monkeyrunner-test "$file"
    echo ''
done
